name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    env:
      TF_VAR_owner: ${{ vars.TF_VAR_OWNER }}
      TF_VAR_resource_group_name: ${{ vars.TF_VAR_RESOURCE_GROUP_NAME }}
      TF_VAR_location: ${{ vars.TF_VAR_LOCATION }}
      TF_VAR_node_resource_group_name: ${{ vars.TF_VAR_NODE_RESOURCE_GROUP_NAME }}
      TF_VAR_employes_group_object_id: ${{ vars.TF_VAR_EMPLOYES_GROUP_OBJECT_ID }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Login Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Format Check
        run: terraform fmt -check -diff -recursive
        continue-on-error: true

      - name: Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: starter/terraform
          framework: terraform
          soft_fail: true

      - name: Key Vault Check
        id: check_kv
        run: |
          if az keyvault show --name kv-storage-encrypt-mc &>/dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: "Authorize runner IP on Key Vault"
        if: steps.check_kv.outputs.exists == 'true'
        run: |
          RUNNER_IP=$(curl -s https://api.ipify.org)
          az keyvault network-rule add \
          --name kv-storage-encrypt-mc \
          --ip-address "$RUNNER_IP/32"

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.TF_STATE_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ secrets.TF_STATE_SA_NAME }}" \
            -backend-config="container_name=${{ secrets.TF_STATE_CONTAINER_NAME }}" \
            -backend-config="key=${{ secrets.TF_STATE_KEY }}"

      - name: Terraform Validate
        run: terraform validate
      - name: Remove runner IP from Key Vault (Cleanup)
        if: always() && steps.check_kv.outputs.exists == 'true'
        run: |
          RUNNER_IP=$(curl -s https://api.ipify.org)
          az keyvault network-rule remove \
          --name kv-storage-encrypt-mc \
          --ip-address "$RUNNER_IP/32"
